// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDz8_f-vlM4ICvMlyjeGFd_o30a39Ork4',
    appId: '1:799726750774:web:373e960c28eede60d71c97',
    messagingSenderId: '799726750774',
    projectId: 'towontruck-d0135',
    authDomain: 'towontruck-d0135.firebaseapp.com',
    databaseURL: 'https://towontruck-d0135-default-rtdb.firebaseio.com',
    storageBucket: 'towontruck-d0135.firebasestorage.app',
    measurementId: 'G-0MWZ065SRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh4SumNiUopDFMXw-RydeITSyPVujX2_Q',
    appId: '1:799726750774:android:5143b6e11fb860cad71c97',
    messagingSenderId: '799726750774',
    projectId: 'towontruck-d0135',
    databaseURL: 'https://towontruck-d0135-default-rtdb.firebaseio.com',
    storageBucket: 'towontruck-d0135.firebasestorage.app',
  );
}
